/**
 * @file This file contains mock data used for integration tests.
 * ALL DATA has been refactored to the new 21-column layout.
 */

const MOCK_DATA_INTEGRATION = {
  groupingTestsAsArray: [
    [
      "SKU",
      "EP CAPEX",
      "Telekom CAPEX",
      "Target",
      "Limit",
      "Index",
      "Bundle Number",
      "Device",
      "AE CAPEX",
      "AE SALES ASK",
      "QUANTITY",
      "TERM",
      "APPROVER_ACTION",
      "APPROVER_COMMENTS",
      "APPROVER_PRICE_PROPOSAL",
      "LRF_PREVIEW",
      "CONTRACT_VALUE",
      "STATUS",
      "FINANCE_APPROVED_PRICE",
      "APPROVED_BY",
      "APPROVAL_DATE",
    ],
    [
      "SKU-A",
      "",
      "",
      "",
      "",
      "1",
      "",
      "Individual Approved A",
      1000,
      50.0,
      1,
      24,
      "Choose Action",
      "",
      "",
      "",
      "",
      "Approved (Original Price)",
      50.0,
      "approver@test.com",
      "2025-01-01",
    ],
    [
      "SKU-B",
      "",
      "",
      "",
      "",
      "2",
      "101",
      "Complete Bundle A (Cheaper)",
      1200,
      25.5,
      10,
      24,
      "Choose Action",
      "",
      "",
      "",
      "",
      "Approved (Original Price)",
      25.5,
      "approver@test.com",
      "2025-01-01",
    ],
    [
      "SKU-C",
      "",
      "",
      "",
      "",
      "3",
      "101",
      "Complete Bundle B (Pricier)",
      1200,
      30.0,
      10,
      24,
      "Choose Action",
      "",
      "",
      "",
      "",
      "Approved (New Price)",
      30.0,
      "approver@test.com",
      "2025-01-01",
    ],
    [
      "SKU-D",
      "",
      "",
      "",
      "",
      "4",
      "",
      "Individual Draft",
      1500,
      40.0,
      1,
      24,
      "Choose Action",
      "",
      "",
      "",
      "",
      "Draft",
      "",
      "",
      "",
    ],
    [
      "SKU-E",
      "",
      "",
      "",
      "",
      "5",
      "",
      "Individual Approved B",
      2000,
      100.0,
      2,
      36,
      "Choose Action",
      "",
      "",
      "",
      "",
      "Approved (New Price)",
      100.0,
      "approver@test.com",
      "2025-01-01",
    ],
    [
      "SKU-F",
      "",
      "",
      "",
      "",
      "6",
      "202",
      "Incomplete Bundle A (Approved)",
      800,
      15.0,
      5,
      12,
      "Choose Action",
      "",
      "",
      "",
      "",
      "Approved (Original Price)",
      15.0,
      "approver@test.com",
      "2025-01-01",
    ],
    [
      "SKU-G",
      "",
      "",
      "",
      "",
      "7",
      "202",
      "Incomplete Bundle B (Pending)",
      800,
      20.0,
      5,
      12,
      "Choose Action",
      "",
      "",
      "",
      "",
      "Pending Approval",
      "",
      "",
      "",
    ],
  ],

  csvForApprovalWorkflowTests: `SKU,EP CAPEX,Telekom CAPEX,Target,Limit,Index,Bundle Number,Device,AE CAPEX,AE SALES ASK,QUANTITY,TERM,APPROVER_ACTION,APPROVER_COMMENTS,APPROVER_PRICE_PROPOSAL,LRF_PREVIEW,CONTRACT_VALUE,STATUS,FINANCE_APPROVED_PRICE,APPROVED_BY,APPROVAL_DATE
SKU-01,"","","","",1,,"Device A",1200,"100","10","24","Choose Action","","","","",Pending Approval,"","",""
SKU-02,"","","","",2,,"Device B",900,"80","12","24","Choose Action","","90","","",Pending Approval,"","",""
`,

  csvForHealthCheckTests: [
    [
      "SKU",
      "EP CAPEX",
      "TK CAPEX",
      "Target",
      "Limit",
      "Index",
      "Bundle Number",
      "Model",
      "AE CAPEX",
      "AE SALES ASK",
      "Qty",
      "Term",
      "Action",
      "Comments",
      "Approver Price",
      "LRF",
      "Contract Value",
      "Status",
      "Finance Price",
      "Approved By",
      "Approval Date",
    ],
    [
      "SKU-01",
      "",
      "",
      "",
      "",
      1,
      "",
      "Approved but no date",
      1200,
      100,
      10,
      24,
      "Choose Action",
      "",
      "",
      "",
      "",
      "Approved (Original Price)",
      100,
      "approver@test.com",
      "",
    ],
    [
      "SKU-02",
      "",
      "",
      "",
      "",
      2,
      "",
      "Healthy approved row",
      900,
      80,
      12,
      24,
      "Choose Action",
      "",
      "",
      "",
      "",
      "Approved (Original Price)",
      80,
      "approver@test.com",
      "2025-01-01",
    ],
    [
      "SKU-03",
      "",
      "",
      "",
      "",
      3,
      "",
      "Rejected but no date",
      600,
      50,
      5,
      36,
      "Choose Action",
      "",
      "",
      "",
      "",
      "Rejected",
      "",
      "approver@test.com",
      "",
    ],
  ],

    csvForUxControlTests:
`SKU,EP CAPEX,Telekom CAPEX,Target,Limit,Index,Bundle Number,Device,AE CAPEX,AE SALES ASK,QUANTITY,TERM,APPROVER_ACTION,APPROVER_COMMENTS,APPROVER_PRICE_PROPOSAL,LRF_PREVIEW,CONTRACT_VALUE,STATUS,FINANCE_APPROVED_PRICE,APPROVED_BY,APPROVAL_DATE
SKU-DRAFT,,,,,"1",,"Draft Device",,100,10,24,"Choose Action","","","","","",Draft
SKU-PEND,,,,,"2",,"Pending Device",1000,100,10,24,"Choose Action","","","","","",Pending Approval
SKU-APP-O,,,,,"3",,"Approved (O) Device",1000,100,10,24,"Choose Action","","","","","",Approved (Original Price)
,,,,,"4",,"No Status Row",,,,,,,,,,,,
SKU-REJ,,,,,"5",,"Rejected Device",1000,100,10,24,"Choose Action","","","","",Rejected
SKU-REV-AE,,,,,"6",,"Revised AE Device",1000,100,10,24,"Choose Action","","","","",Revised by AE
`,

  csvForSanitizationTests: `SKU,EP CAPEX,TK CAPEX,Target,Limit,Index,Bundle Number,Model,AE CAPEX,AE SALES ASK,Qty,Term,Action,Comments,Approver Price,LRF,Contract Value,Status,Finance Price,Approved By,Approval Date
S1_SOURCE_APPROVED,900,850,45,40,16,,Source Approved Model,900,50,20,24,"Choose Action",,"",1.2,21600,Approved (Original Price),50,approver@test.com,2025-07-21
S2_TARGET_APPROVED,1200,1100,65,60,17,,Target Approved Model,1200,70,10,36,"Choose Action",,"",1.4,25200,Approved (Original Price),70,approver@test.com,2025-07-22
S1_DESTINATION_BLANK,,,,,,,,,,,,,,,,,,,
S4_TARGET_PENDING,500,450,25,20,18,,Target Pending Model,500,30,5,12,"Choose Action",,"",0.72,1800,Pending Approval,,,
S5_PASTE_SOURCE,,,,,99,,Pasted Model For S5,600,35,7,18,"Choose Action",,,,,,,,,
`,

  csvForBundleValidationTests: `SKU,EP CAPEX,Telekom CAPEX,Target,Limit,Index,Bundle Number,Device,AE CAPEX,AE SALES ASK,QUANTITY,TERM,APPROVER_ACTION,APPROVER_COMMENTS,APPROVER_PRICE_PROPOSAL,LRF_PREVIEW,CONTRACT_VALUE,STATUS,FINANCE_APPROVED_PRICE,APPROVED_BY,APPROVAL_DATE
,,,,,"1",101,"Valid Bundle A",1000,"",10,24,,,,,,
,,,,,"2",101,"Valid Bundle B",1000,"",10,24,,,,,,
,,,,,"3",,"Single Item",1000,"",1,12,,,,,,
,,,,,"4",202,"Valid Bundle C1",1000,"",5,36,,,,,,
,,,,,"5",202,"Valid Bundle C2",1000,"",5,36,,,,,,
,,,,,"6",202,"Valid Bundle C3",1000,"",5,36,,,,,,
,,,,,"7",303,"Single w/ Bundle #",1000,"",1,24,,,,,,
,,,,,"8",404,"Non-Consecutive A",1000,"",2,24,,,,,,
,,,,,"9",999,"INTERRUPTING ROW",1000,"",99,99,,,,,,
,,,,,"10",404,"Non-Consecutive B",1000,"",2,24,,,,,,
,,,,,"11",505,"Mismatch Qty A",1000,"",15,24,,,,,,
,,,,,"12",505,"Mismatch Qty B",1000,"",16,24,,,,,,
,,,,,"13",606,"Mismatch Term A",1000,"",20,24,,,,,,
,,,,,"14",606,"Mismatch Term B",1000,"",20,36,,,,,,
`,
};
